version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test-task-db
      MYSQL_TCP_PORT: 3300
    ports:
      - "3300:3300"
    expose:
      - "3300"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: